### ISSUE TITLE
`Symbol.asyncDispose` vs `.disposeAsync()` - why names are inconsistent?

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-async-explicit-resource-management#2]
^

**Comment by rbuckton** [comment]
It is often a common practice to have string-named async methods have a trailing `Async` in the name (i.e., [`Atomics.waitAsync`](https://github.com/tc39/proposal-atomics-wait-async), [`Array.fromAsync`](https://github.com/tc39/proposal-array-from-async), etc.). For the symbol name, I chose to match precedent of `[Symbol.iterator]()` and `[Symbol.asyncIterator]()`.

**Comment by zloirock** [comment]
I agree that this convention is a good option in most cases, but here it's methods of one object and it looks weird.

Anyway, it's not something critical for me.

**Comment by Jamesernator** [comment]
This might be too late to change, but shouldn't `Symbol.{async}dispose` really be `Symbol.{async}disposer`, i.e. using nouns rather than verbs like `Symbol.{async}iterator`. (Like the iterator symbols aren't called `Symbol.{async}iterate`).

With this naming, `Symbol.{async}disposer` would return a *disposer* [a noun] function, and `.dispose{Async}` would actually perform [a verb] the disposal action.

**Comment by bakkot** [comment]
@Jamesernator generally the choice of semantics should come prior to the choice of naming. And the obvious semantics in this case are that you have a function you call to do the disposal, not that you have a function you call to get a function you call to do the disposal - there's no reason for that extra layer of indirection.

And once that's settled, `Symbol.dispose` and `Symbol.asyncDispose` are the obvious names for that function you call to do the disposal.

**Comment by Jamesernator** [comment]
> not that you have a function you call to get a function you call to do the disposal - there's no reason for that extra layer of indirection.

It appears I've misread the explainer, I was thinking that it worked like:

```js
using {await} x = getX();

// Would become

const x = getX();
const x$disposer = x[Symbol.{async}dipose]();
try {
    // ... rest of block
} finally {
    {await} x$disposer();
}
```

but rather it's just `const x$disposer = x[Symbol.{async}dispose]`.

In that case I'd agree with the initial issue that really it should be `Symbol.disposeAsync` given it doesn't actually behave like the iterator methods at all (like the iterator methods both produce objects synchronously and don't neccessarily imply async work).

**Comment by rbuckton** [comment]
I'll bring this up in plenary.

**Comment by rbuckton** [comment]
We discussed this in the January plenary and the consensus was to remain consistent with `Symbol.iterator`/`Symbol.asyncIterator` for the symbol name.
